# Usar uma imagem base do Python
FROM python:3.9-slim

# Configurar o diretório de trabalho
WORKDIR /app

# Copiar o script mascara.py para o container
COPY mascara.py /app/mascara.py

# Configurar o comando de execução do script
CMD ["python", "mascara.py"]
