# Usar uma imagem base do Python
FROM python:3.9-slim

# Configurar o diretório de trabalho
WORKDIR /app

# Copiar o arquivo carguru.py para o container
COPY carguru.py /app/carguru.py

# Configurar o comando de execução do script
CMD ["python", "carguru.py"]
